version: '3'
services:
  app:
    image: node:10
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment: 
      NODE_ENV: prod
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes: 
      - ./var/lib/mongodb:/data/db
    ports:
      - '27017:27017'